---
config:
  theme: neutral
  look: classic
  themeVariables:
    fontFamily: "Comic Sans MS"
    fontSize: "10px"
    # Your specific Green
    primaryColor: "#002199ff"
    # Your specific Purple (cleaned to 6-digit hex for compatibility)
    lineColor: "#ba4700ff"
    # Ensuring the text is sharp and dark
    textColor: "#007a06da"
  ishikawa:
    edgeLength: 50
    mirror: true
---
ishikawa
  Failure
      Maintenance
          Broken<br/>parts
          Outdated<br/>firmware
      Personnel
          Lack of<br/>training
          Lack of<br/>skills
      Environment
          Temperature
          High<br/>Humidity
      Effect
          Process <br/>failure