---
config:
  theme: neutral
  themeVariables:
    fontFamily: "'Source Code Pro', monospace"
    pie1: "#60a5fa"
    pie2: "#3b82f6"
    pie3: "#2563eb"
    pie4: "#1d4ed8"
    pie5: "#1e40af"
    pie6: "#1e3a8a"
    pie10: "#000000"
    pieBorder: "#111827"
---
pie title Sales
    'Dogs' : 386
    'Cats' : 85 
    'Birds' : 23
    'Fishes' : 12
